version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_DB_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
#  app:
#    build:
#      context: .
#    ports:
#      - "8000:8000"
